spring:
  application:
    name: delivery-system
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
delivery-system:
  value: "VALOR - DEFAULT"
  default-value: "VALOR DEFAULT - DEFAULT"
